-- IDs and kinds only: deleted private content is never copied into this log.
CREATE TABLE library_sync_state(id INTEGER PRIMARY KEY CHECK(id=1),epoch TEXT NOT NULL,floor INTEGER NOT NULL DEFAULT 0);
INSERT INTO library_sync_state(id,epoch) VALUES(1,lower(hex(randomblob(16))));
CREATE TABLE library_sync_changes(seq INTEGER PRIMARY KEY AUTOINCREMENT,link_id INTEGER,kind TEXT NOT NULL CHECK(kind IN ('upsert','delete','taxonomy')),created_at INTEGER NOT NULL DEFAULT(unixepoch()));
CREATE INDEX library_sync_retention ON library_sync_changes(created_at,seq);
INSERT INTO library_sync_changes(link_id,kind) SELECT id,'upsert' FROM links;
CREATE TRIGGER library_sync_links_insert AFTER INSERT ON links BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.id,'upsert'); END;
CREATE TRIGGER library_sync_links_update AFTER UPDATE ON links BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.id,'upsert'); END;
CREATE TRIGGER library_sync_links_delete AFTER DELETE ON links BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(OLD.id,'delete'); END;
CREATE TRIGGER library_sync_curation_overrides_insert AFTER INSERT ON curation_overrides BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_curation_overrides_update AFTER UPDATE ON curation_overrides BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_curation_overrides_delete AFTER DELETE ON curation_overrides BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(OLD.link_id,'upsert'); END;
CREATE TRIGGER library_sync_classification_decisions_insert AFTER INSERT ON classification_decisions BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_classification_decisions_update AFTER UPDATE ON classification_decisions BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_classification_decisions_delete AFTER DELETE ON classification_decisions BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(OLD.link_id,'upsert'); END;
CREATE TRIGGER library_sync_entity_states_insert AFTER INSERT ON entity_states BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_entity_states_update AFTER UPDATE ON entity_states BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_entity_states_delete AFTER DELETE ON entity_states BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(OLD.link_id,'upsert'); END;
CREATE TRIGGER library_sync_evidence_snapshots_insert AFTER INSERT ON evidence_snapshots BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_evidence_snapshots_update AFTER UPDATE ON evidence_snapshots BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_evidence_snapshots_delete AFTER DELETE ON evidence_snapshots BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(OLD.link_id,'upsert'); END;
CREATE TRIGGER library_sync_link_selections_v2_insert AFTER INSERT ON link_selections_v2 BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_link_selections_v2_update AFTER UPDATE ON link_selections_v2 BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_link_selections_v2_delete AFTER DELETE ON link_selections_v2 BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(OLD.link_id,'upsert'); END;
CREATE TRIGGER library_sync_custom_tag_links_insert AFTER INSERT ON custom_tag_links BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_custom_tag_links_update AFTER UPDATE ON custom_tag_links BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_custom_tag_links_delete AFTER DELETE ON custom_tag_links BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(OLD.link_id,'upsert'); END;
CREATE TRIGGER library_sync_effective_tag_memberships_insert AFTER INSERT ON effective_tag_memberships BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_effective_tag_memberships_update AFTER UPDATE ON effective_tag_memberships BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_effective_tag_memberships_delete AFTER DELETE ON effective_tag_memberships BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(OLD.link_id,'upsert'); END;
CREATE TRIGGER library_sync_legacy_curation_history_insert AFTER INSERT ON legacy_curation_history BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_legacy_curation_history_update AFTER UPDATE ON legacy_curation_history BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(NEW.link_id,'upsert'); END;
CREATE TRIGGER library_sync_legacy_curation_history_delete AFTER DELETE ON legacy_curation_history BEGIN INSERT INTO library_sync_changes(link_id,kind) VALUES(OLD.link_id,'upsert'); END;
CREATE TRIGGER library_sync_custom_tags_insert AFTER INSERT ON custom_tags BEGIN INSERT INTO library_sync_changes(kind) VALUES('taxonomy'); INSERT INTO library_sync_changes(link_id,kind) SELECT link_id,'upsert' FROM custom_tag_links WHERE tag_id=NEW.id; END;
CREATE TRIGGER library_sync_custom_tags_update AFTER UPDATE ON custom_tags BEGIN INSERT INTO library_sync_changes(kind) VALUES('taxonomy'); INSERT INTO library_sync_changes(link_id,kind) SELECT link_id,'upsert' FROM custom_tag_links WHERE tag_id=NEW.id; END;
CREATE TRIGGER library_sync_custom_tags_delete AFTER DELETE ON custom_tags BEGIN INSERT INTO library_sync_changes(kind) VALUES('taxonomy'); INSERT INTO library_sync_changes(link_id,kind) SELECT link_id,'upsert' FROM custom_tag_links WHERE tag_id=OLD.id; END;
CREATE TRIGGER library_sync_taxonomy_display_overrides_insert AFTER INSERT ON taxonomy_display_overrides BEGIN INSERT INTO library_sync_changes(kind) VALUES('taxonomy'); END;
CREATE TRIGGER library_sync_taxonomy_display_overrides_update AFTER UPDATE ON taxonomy_display_overrides BEGIN INSERT INTO library_sync_changes(kind) VALUES('taxonomy'); END;
CREATE TRIGGER library_sync_taxonomy_display_overrides_delete AFTER DELETE ON taxonomy_display_overrides BEGIN INSERT INTO library_sync_changes(kind) VALUES('taxonomy'); END;
